[functions]
  directory = "functions"

[[redirects]]
  from = "/notion-api/*"
  to = "https://api.notion.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Headers = "Content-Type, Authorization", Access-Control-Allow-Methods = "GET, POST, OPTIONS"}

# SPA fallback 설정: 위의 redirect 규칙보다 아래에 작성합니다.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
